//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drug()
        {
            this.PrescribeDrugs = new HashSet<PrescribeDrug>();
        }
    
        public int ID { get; set; }
        public int ISSN { get; set; }
        public string Name { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int Quantity { get; set; }
        public decimal sellingPrice { get; set; }
        public decimal BuyingPrice { get; set; }
        public Nullable<int> Pharmcy2ID { get; set; }
        public Nullable<int> ManufactruerID { get; set; }
    
        public virtual DrugManufactruer DrugManufactruer { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescribeDrug> PrescribeDrugs { get; set; }
    }
}
