//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeePhoneNumbers = new HashSet<EmployeePhoneNumber>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string city { get; set; }
        public string Region { get; set; }
        public string Position { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
        public int Salary { get; set; }
        public string ShiftTimeFrom { get; set; }
        public string ShiftTimeTo { get; set; }
        public Nullable<int> Pharmacy_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePhoneNumber> EmployeePhoneNumbers { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
