//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescribeDrug
    {
        public int ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> DrugID { get; set; }
        public Nullable<int> Prescribe_ID { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Prescribe Prescribe { get; set; }
    }
}
